title: tavora.dev/dev
#email: me@tavora.dev
#description: >- # this means to ignore newlines until "baseurl:"
#  tavora website
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://www.tavora.dev/blog" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

show_excerpts: true

collections:
  blog:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

# Needed to paginate the list of posts in the homepage
paginate: 5

paginate_path: "/blog/page:num/"

# Allowed categories
categories:
  - blog
